name: Maven CI workflow

on: push

jobs:
  maven_ci:
    name: Maven CI job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          cache: maven
      - name: Maven
        run: mvn -B verify

